-- 코드를 입력하세요
--LINK: https://school.programmers.co.kr/learn/courses/30/lessons/59413#
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
),
EXAMPLE AS (
    SELECT 
        HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
)
SELECT 
    H.HOUR,
    COALESCE(COUNT(E.HOUR), 0) AS COUNT
FROM HOURS H
LEFT JOIN EXAMPLE E ON H.HOUR = E.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR;