-- 코드를 작성해주세요

WITH EXAMPLE AS (
    SELECT 
        I.ID, 
        N.FISH_NAME,
        I.FISH_TYPE,
        I.LENGTH,
        ROW_NUMBER() OVER (PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS RN
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
)
SELECT 
    ID,
    FISH_NAME,
    LENGTH
FROM EXAMPLE
WHERE RN = 1
ORDER BY ID;
    