-- LINK:https://school.programmers.co.kr/learn/courses/30/lessons/298519
-- 코드를 작성해주세요
WITH EXAMPLE AS (
SELECT 
    FISH_TYPE,
    COUNT(FISH_TYPE) AS FISH_COUNT,
    AVG(COALESCE(LENGTH, 10)) AS AVG_LENGTH,
    MAX(COALESCE(LENGTH,10)) AS MAX_LENGTH
FROM FISH_INFO 
GROUP BY FISH_TYPE
)
SELECT 
    FISH_COUNT,
    MAX_LENGTH,
    FISH_TYPE
FROM EXAMPLE
WHERE AVG_LENGTH >=33
ORDER BY FISH_TYPE;
